apiVersion: batch/v1
kind: Job
metadata:
  name: create-topic
  namespace: gpu-pipeline
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: create-topic
          image: curlimages/curl
          command:
            - sh
            - -c
            - |
              sleep 10
              echo "Creating telemetry topic with 3 partitions..."
              curl -X POST http://mq-service:8080/topics \
              -H "Content-Type: application/json" \
              -d '{"name":"telemetry","partitions":3}'
              echo "Topic created successfully"
      restartPolicy: Never