apiVersion: v1
kind: Service
metadata:
  name: mq-service
  namespace: {{ .Values.namespace }}
  labels:
    app: mq
spec:
  type: NodePort
  ports:
    - port: {{ .Values.mq.port }}
      targetPort: {{ .Values.mq.port }}
      protocol: TCP
      name: http
  selector:
    app: mq
